trade_settings:
  stop_loss:
    enabled: true
    mode: atr
    value: 14
    multiplier: 1
  take_profit:
    enabled: true
    mode: atr
    value: 14
    multiplier: 2
  fees:  # only for backtesting
    enabled: true
    mode: "percentage"  # "percentage" or "fixed"
    maker: 0.1
    taker: 0.2
  position_size:
    enabled: true
    mode: "percentage"  # "percentage" or "fixed"
    value: 0.01  # 0.01 = 1% of the balance if mode is "percentage"
predictor_settings:  # only for training
  horizon: 10  # number of candles to look in the front (forward looking)
  estimator_type:  "classification"  # "classification"
  mode: "risk_reward"
  thresholds:
    strong_sell: -10.0  # rr-ratio > 2, i.e. risk is 1 and reward is 2
    sell:  -5.0  # rr-ratio > 2, i.e. risk is 1 and reward is 2
    buy: 5.0  # rr-ratio > 2, i.e. risk is 1 and reward is 2
    strong_buy: 10.0  # rr-ratio > 2, i.e. risk is 1 and reward is 2
feature_settings:  # machine learning features
  - name: "atr"
    parameters:
      atr_period: 14
  - name: "smoothed_ha"
    parameters:
      ha_smooth_length: 10
  - name: "sharpe_ratio"
    parameters:
      periods_count: 50
      annual_risk_free_percent: 2.0
  - name: "sortino_ratio"
    parameters:
      periods_count: 50
      annual_risk_free_percent: 2.0
  - name: "squeeze_momentum"
    parameters:
      bb_length: 20
      bb_mult_factor: 2
      kc_length: 20
      kc_mult_factor: 1.5
      linreg_window: 10
#  - name: "super_trend"
#    parameters:
#      factor: 3.0
#      atr_period: 10
  - name: "adaptive_super_trend"
    parameters:
      factor: 3.0
      atr_period: 10
      training_data_period: 100
model_settings:
  model_type: "random_forest" # need to be registered (none) for no model"
  parameters:
    # depends on the model
