from enum import Enum


class MarketStatus(Enum):
    CLOSED = "CLOSED"
    EDITS_ONLY = "EDITS_ONLY"
    OFFLINE = "OFFLINE"
    ON_AUCTION = "ON_AUCTION"
    ON_AUCTION_NO_EDITS = "ON_AUCTION_NO_EDITS"
    SUSPENDED = "SUSPENDED"
    TRADEABLE = "TRADEABLE"
