name: Pre-commit

on:
  pull_request:  # triggers on all PRs to any branch

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pip install -r requirements_dev.txt

      - name: Run pre-commit checks
        run: pre-commit run --all-files
